### ISSUE TITLE
helm-snyk-macos Not Found

### ISSUE THREAD

**Issue by sc-steven** [snyk-labs/helm-snyk#35]
After following the install instructions and everything looking great, i attempt to run the "helm snyk test" command get the following.

`/Users/username/Library/helm/plugins/helm-snyk/bin/helm-snyk-macos: line 1: Not: command not found
Error: plugin "snyk" exited with error`

When i open the file helm-snyk-macos it only contains "Not Found"

**Comment by sc-steven** [comment]
I did a manual wget of `https://github.com/snyk-labs/helm-snyk/releases/download/v1.2.4/helm-snyk-macos` and `chmod a+x helm-snyk-macos` in order to get it working.

**Comment by agranado2k** [comment]
Hi @sc-steven,

We've just released a new plugin version that solve this issue. Could you update the plugin with follow command, please?

```
helm plugin update snyk
```
